/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MapRouteImport } from './routes/map'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileSettingsRouteImport } from './routes/profile_.settings'
import { Route as ChatsIdRouteImport } from './routes/chats.$id'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile_/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsIdRoute = ChatsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChatsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRouteWithChildren
  '/map': typeof MapRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/chats/$id': typeof ChatsIdRoute
  '/profile/settings': typeof ProfileSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRouteWithChildren
  '/map': typeof MapRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/chats/$id': typeof ChatsIdRoute
  '/profile/settings': typeof ProfileSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chats': typeof ChatsRouteWithChildren
  '/map': typeof MapRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/chats/$id': typeof ChatsIdRoute
  '/profile_/settings': typeof ProfileSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chats'
    | '/map'
    | '/orders'
    | '/profile'
    | '/chats/$id'
    | '/profile/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chats'
    | '/map'
    | '/orders'
    | '/profile'
    | '/chats/$id'
    | '/profile/settings'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chats'
    | '/map'
    | '/orders'
    | '/profile'
    | '/chats/$id'
    | '/profile_/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatsRoute: typeof ChatsRouteWithChildren
  MapRoute: typeof MapRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile_/settings': {
      id: '/profile_/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/$id': {
      id: '/chats/$id'
      path: '/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof ChatsIdRouteImport
      parentRoute: typeof ChatsRoute
    }
  }
}

interface ChatsRouteChildren {
  ChatsIdRoute: typeof ChatsIdRoute
}

const ChatsRouteChildren: ChatsRouteChildren = {
  ChatsIdRoute: ChatsIdRoute,
}

const ChatsRouteWithChildren = ChatsRoute._addFileChildren(ChatsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatsRoute: ChatsRouteWithChildren,
  MapRoute: MapRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
